import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "tfg No me acuerdo el nombre",
  description: "Generated by create next app, designed by Jaime Quer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body>
        {children}
      </body>
    </html>
  );
}
